### ISSUE TITLE
PowerShell5 install fails with 2359302 exit code

### ISSUE THREAD

**Issue by rschiefer** [chef-cookbooks/powershell#48] opened 2015-08-04 17:17 UTC
The following post specifies the 2359302 exit code indicates the update is already installed which is true in my case.  

http://answers.microsoft.com/en-us/windows/forum/all/eventvwr-shows-2359302-errorcode/51658f7b-651a-4c7b-b5fd-001f58ccca8d

The cookbook should accept this exit code and pass successfully.

**Comment by bheuvel** [comment] 2015-09-09 13:32
Seems related to #40 ?
But perhaps there's (also) something off with the installer, cause when installing by hand I get:
```
C:\>start /wait c:\WindowsBlue-KB3037315-x64.msu /quiet /norestart & echo %ERRORLEVEL%
0

C:\>start /wait c:\WindowsBlue-KB3037315-x64.msu /quiet /norestart & echo %ERRORLEVEL%
3010

C:\>start /wait c:\WindowsBlue-KB3037315-x64.msu /quiet /norestart & echo %ERRORLEVEL%
2359302
```
The first is the regular install.
The second is the standard code that states you need to reboot.

Even with a reboot in between, after a few times it always gets to 2359302

**Comment by MattHodge** [comment] 2015-10-13 20:14
For a temporary fix you can put the following in an attribute file:

```ruby
# For PowerShell Production Preview x64 on Windows 8.1 or Win2012R2
default['powershell']['powershell5']['version'] = '5.0.10514.6'
default['powershell']['powershell5']['url'] = 'https://download.microsoft.com/download/3/F/D/3FD04B49-26F9-4D9A-8C34-4533B9D5B020/Win8.1AndW2K12R2-KB3066437-x64.msu'
default['powershell']['powershell5']['checksum'] = '9c57302ff0515a6b7eb53ab07bed0f5d420bd7204296d9f3fd17452fca1d5b3d'
```

**Comment by RyanJarv** [comment] 2015-10-22 23:52
Note that these attributes are not available in the currently released version of this cookbook (3.1.0) you need to be on master to set ['powershell']['powershell5']['version']

**Comment by smurawski** [comment] 2015-12-16 17:35
If the guard is not having the desired effect, we should change the guard clause.  I'll try this out.

**Comment by smurawski** [comment] 2015-12-16 17:42
This is a duplicate of #40.  Closing in favor of the older bug with more history.  I'll continue to test.

**Closed by smurawski** 2015-12-16 17:42 UTC
